Suggestion page
WildCodeSchool/2022-03-JS-Lille-project-2-g3-movies pull request #13
Opened 2022-04-21 08:26 UTC by Elfaram

2022-04-21 12:02 UTC, NtGZeko approved these changes, later dismissed

2022-04-21 13:08 UTC, LuigiMenez commented on frontend/package.json
> +    "template-fullstack": "file:.."
Nope

2022-04-21 13:08 UTC, LuigiMenez commented on backend/package.json
> +    "template-fullstack": "file:.."
Nope

2022-04-21 13:10 UTC, LuigiMenez requested changes
Remove a package template fullstack

2022-04-21 13:27 UTC, NtGZeko submitted a review, later dismissed

2022-04-21 14:29 UTC, LuigiMenez submitted a review, later dismissed
Ok for me

2022-04-21 15:23 UTC, LoicBrassart approved these changes, later dismissed
Saw no Evil

2022-04-21 19:21 UTC, Dash293 submitted a review, later dismissed

2022-04-21 19:22 UTC, NtGZeko approved these changes, later dismissed

2022-04-21 19:57 UTC, SDecambray approved these changes, later dismissed

2022-04-22 05:27 UTC, LoicBrassart commented
Beware: when you want to leave a positive review, don't forget to click the "Approve" button, otherwise it doesn't validate the PR

2022-04-22 07:22 UTC, NtGZeko approved these changes

2022-04-22 07:26 UTC, LoicBrassart approved these changes
Beware, you ad a lot of empty lines when solving conflicts. No Evil spotted otherwise !

2022-04-22 07:27 UTC, merged