Adding styled-component + styled-reset in oackages and a line in fron…
WildCodeSchool/2022-03-JS-Lille-project-2-g3-movies pull request #2
Opened 2022-04-06 15:12 UTC by ilalande

…tend/index with a script to add fontawesome.

2022-04-07 13:46 UTC, SDecambray commented
Okey

2022-04-07 13:46 UTC, SDecambray submitted a review, later dismissed

2022-04-08 07:01 UTC, LuigiMenez commented on frontend/index.html
> +      src="https://kit.fontawesome.com/f831de03a8.js"
Not good way import with React

2022-04-08 07:01 UTC, LuigiMenez requested changes
Not good Way import with react

2022-04-08 12:19 UTC, SDecambray submitted a review, later dismissed

2022-04-08 13:36 UTC, LuigiMenez submitted a review, later dismissed
Ok

2022-04-11 07:39 UTC, SDecambray approved these changes, later dismissed
okey

2022-04-11 10:11 UTC, LuigiMenez submitted a review, later dismissed
Ok for me

2022-04-12 09:16 UTC, LoicBrassart requested changes
A bit of cleanup to do ;-)

2022-04-12 09:16 UTC, LoicBrassart commented on package.json
> +    "@fortawesome/react-fontawesome": "^0.1.18"
Nope, you don't need these packages in the root package.json, they should be in the `frontend` one (React needs it, your backend doesn't)

2022-04-12 09:17 UTC, LoicBrassart commented
@LuigiMenez Beware of *which* `package.json` holds the new installations, it can lead to serious bugs

2022-04-12 13:06 UTC, SDecambray approved these changes

2022-04-12 13:09 UTC, LuigiMenez approved these changes
Ok for me

2022-04-12 14:29 UTC, LoicBrassart approved these changes
No more Evils !
You don't use FAwesome in the end ?

2022-04-12 14:32 UTC, merged

2022-04-13 09:36 UTC, ilalande commented
@LoicBrassart  No, too much time spent on it :-)