Puting all images and links in type carousel
WildCodeSchool/2022-03-JS-Lille-project-2-g3-movies pull request #20
Opened 2022-04-26 09:44 UTC by ilalande

2022-04-26 21:07 UTC, LuigiMenez requested changes
Not seen by the DM

2022-04-27 07:33 UTC, Dash293 submitted a review, later dismissed

2022-04-27 12:58 UTC, LuigiMenez commented on frontend/src/components/TypeCarroussel/index.jsx
> +        <SwiperSlide>
use .map method

2022-04-27 12:58 UTC, LuigiMenez requested changes
Use .map method

2022-04-27 13:30 UTC, Dash293 approved these changes

2022-04-27 13:46 UTC, LuigiMenez approved these changes
Ok for me

2022-04-27 16:50 UTC, LoicBrassart approved these changes
Saw no Evil

2022-04-28 09:01 UTC, merged