Suggest page1.0
WildCodeSchool/2022-03-JS-Lille-project-2-g3-movies pull request #26
Opened 2022-04-28 08:48 UTC by ilalande

2022-04-28 09:07 UTC, Elfaram approved these changes

2022-04-28 09:19 UTC, LuigiMenez requested changes
Optimsation possible, in created components smiley with props

2022-05-03 07:13 UTC, Elfaram approved these changes

2022-05-03 09:26 UTC, LuigiMenez approved these changes
Ok for me.

2022-05-03 10:32 UTC, LoicBrassart approved these changes
Saw no Evil

2022-05-03 14:49 UTC, merged