Result suggest
WildCodeSchool/2022-03-JS-Lille-project-2-g3-movies pull request #27
Opened 2022-04-28 09:05 UTC by ilalande

2022-04-28 09:07 UTC, SDecambray submitted a review, later dismissed

2022-04-28 19:23 UTC, LuigiMenez commented on frontend/src/App.jsx
Attention, blank line

2022-04-28 19:26 UTC, LuigiMenez approved these changes, later dismissed
Ok for me

2022-04-28 19:57 UTC, LoicBrassart requested changes
Clean up your fragments ;-)

2022-04-28 19:57 UTC, LoicBrassart commented on frontend/src/App.jsx
> +        <Route path="/suggestion/results" element={<SuggestionResultPage />} />
Indentation is off?

2022-04-28 19:57 UTC, LoicBrassart commented on frontend/src/pages/SuggestionResultPage.jsx
> +    <>
Useless Fragment (it's wrap ping à solo jsxnode)

2022-04-28 19:57 UTC, LoicBrassart commented on frontend/src/pages/Suggestion.jsx
> +    <>
Useless fragment, it's wrap ping à solo El e ment

2022-04-29 10:04 UTC, SDecambray submitted a review, later dismissed

2022-05-02 10:38 UTC, LoicBrassart approved these changes, later dismissed
Better!

2022-05-02 10:48 UTC, LuigiMenez submitted a review, later dismissed
Ok for me

2022-05-02 13:37 UTC, SDecambray approved these changes, later dismissed

2022-05-03 14:52 UTC, SDecambray approved these changes

2022-05-04 09:20 UTC, LuigiMenez approved these changes
Ok for me.

2022-05-05 06:54 UTC, LoicBrassart approved these changes
No more Evil

2022-05-05 12:18 UTC, merged