Merge branch 'dev' of github.com:WildCodeSchool/2022-03-JS-Lille-proj…
WildCodeSchool/2022-03-JS-Lille-project-2-g3-movies pull request #35
Opened 2022-05-03 15:35 UTC by Elfaram

…ect-2-g3-movies into dev

2022-05-04 07:26 UTC, SDecambray approved these changes

2022-05-04 08:53 UTC, Elfaram reviewed
Don't valided this PR please ! Thx so much

2022-05-04 09:24 UTC, LuigiMenez approved these changes
Ok for me.

2022-05-05 06:56 UTC, LoicBrassart commented
> Don't valided this PR please ! Thx so much

... Mistranslation, or we should *really* not validate it ? :thinking:

2022-05-05 07:00 UTC, Elfaram commented
You can valided it but i dont think than we ´ll need it. I need to talk with my group before

2022-05-05 07:00 UTC, LoicBrassart commented
> 
Understood, I'll review it anyway

2022-05-05 07:04 UTC, LoicBrassart requested changes
Minor fixes to do

2022-05-05 07:04 UTC, LoicBrassart commented on frontend/src/components/QuestionSug/style.jsx
> +  Img {
`Img` should be `img` (the html tag) *or* `.Img` (a class name (albeit a bad one))

2022-05-05 07:04 UTC, LoicBrassart commented on frontend/src/components/QuestionSug/style.jsx
> +  .button {
Plz find class names which ae not html tags, it's confusing

2022-05-06 15:15 UTC, closed without merging