Suggest page comp
WildCodeSchool/2022-03-JS-Lille-project-2-g3-movies pull request #37
Opened 2022-05-04 08:48 UTC by ilalande

2022-05-04 09:01 UTC, Elfaram approved these changes

2022-05-04 09:11 UTC, LuigiMenez commented on frontend/src/components/QuestionSugComp/style.jsx
> +
Attention a blank Line

2022-05-04 09:15 UTC, LuigiMenez requested changes
Remove blank line please.

2022-05-05 12:15 UTC, julianecasier commented
We put this in hold (we'll use it later) we moved in another direction.

2022-05-06 15:16 UTC, closed without merging