Suggest page4
WildCodeSchool/2022-03-JS-Lille-project-2-g3-movies pull request #41
Opened 2022-05-04 19:42 UTC by ilalande

New version of the suggestion page, adding the class and a selected input

2022-05-04 20:11 UTC, Elfaram approved these changes, later dismissed

2022-05-05 06:59 UTC, LoicBrassart commented
Plz don't assign me yourself (Luigi'll do it when it's time)

2022-05-05 07:03 UTC, Elfaram commented
...i didn't do this...

2022-05-05 07:12 UTC, LuigiMenez approved these changes, later dismissed
Ok for me.

2022-05-05 08:43 UTC, LoicBrassart requested changes
Some major Evils to fix !

2022-05-05 08:43 UTC, LoicBrassart commented on frontend/src/assets/datasuggest.js
> +    query: "with_genres=80&with_genres=27& with_genres=9648&with_genres=53",
- Never add spaces to an url
- I may be wrong but I think you overwrite the same variable (`with_genre`) over and over, it doesn't send the three categories. Have you tested it ?

2022-05-05 08:43 UTC, LoicBrassart commented on frontend/src/assets/datasuggest.js
> +    query: "release_date.gte=2010-01-01&release_date=2010-01-01",
"Send me movies more recent than 2010-01-01 *and* which went live on 2010-01-01" ? Have you tested it ?

2022-05-05 08:43 UTC, LoicBrassart commented on frontend/src/components/QuestionSug/index.jsx
> +                }}
Simplifiable: `onClick={handleChoiceLinks}`

2022-05-05 08:43 UTC, LoicBrassart commented on frontend/src/components/QuestionSug/index.jsx
> +                }}
Same

2022-05-05 08:43 UTC, LoicBrassart commented on frontend/src/components/QuestionSug/index.jsx
> +                }}
Same

2022-05-05 12:35 UTC, julianecasier commented
> ...i didn't do this...

I did... sorry, noted

2022-05-05 12:44 UTC, Elfaram approved these changes

2022-05-05 14:06 UTC, closed without merging