Film details
WildCodeSchool/2022-03-JS-Lille-project-2-g3-movies pull request #42
Opened 2022-05-05 12:29 UTC by Dash293

2022-05-05 12:41 UTC, Elfaram approved these changes

2022-05-05 22:30 UTC, LuigiMenez commented on frontend/src/components/FilmDetails/index.jsx
> +            alt=""
missing alt, useful for accessibility

2022-05-05 22:31 UTC, LuigiMenez requested changes
missing alt, useful for accessibility

2022-05-06 11:46 UTC, Dash293 reviewed
alt correction

2022-05-06 12:42 UTC, closed without merging