Suggest page5
WildCodeSchool/2022-03-JS-Lille-project-2-g3-movies pull request #44
Opened 2022-05-05 15:09 UTC by ilalande

New release of SuggestPage, using remarks of old PR and working!

2022-05-05 15:10 UTC, Elfaram submitted a review, later dismissed

2022-05-05 22:47 UTC, LuigiMenez submitted a review, later dismissed
Ok for me.

2022-05-06 09:56 UTC, LoicBrassart requested changes
Fixes to do !

2022-05-06 09:56 UTC, LoicBrassart commented on frontend/src/assets/datasuggest.js
> +    query: "release_date.gte=2010-01-01&release_date=2010-01-01",
Nope, won't give the right results

2022-05-06 09:56 UTC, LoicBrassart commented on frontend/src/components/QuestionSug/index.jsx
> +    const allTags = Object.keys(formData); // object.keys gets all keys of an object and puts it into an array
It's `Object.keys()` (the capital O is **important**)

2022-05-06 12:07 UTC, LuigiMenez submitted a review, later dismissed
Ok for me

2022-05-06 12:32 UTC, Elfaram submitted a review, later dismissed

2022-05-06 12:55 UTC, LoicBrassart approved these changes, later dismissed
NmE!

2022-05-06 13:16 UTC, Elfaram submitted a review, later dismissed

2022-05-06 13:17 UTC, ilalande commented
It was validated but merging had to be solved... I did it on my computer and it has to be checked again...

2022-05-06 13:53 UTC, Elfaram approved these changes

2022-05-09 09:43 UTC, LuigiMenez approved these changes
Ok for me.

2022-05-09 14:42 UTC, LoicBrassart approved these changes
SnE

2022-05-09 15:03 UTC, merged