Css page result
WildCodeSchool/2022-03-JS-Lille-project-2-g3-movies pull request #46
Opened 2022-05-05 20:33 UTC by NtGZeko

2022-05-05 21:16 UTC, Elfaram submitted a review, later dismissed

2022-05-05 21:41 UTC, Elfaram approved these changes, later dismissed

2022-05-05 22:20 UTC, LuigiMenez commented on frontend/src/components/FilmDetails/index.jsx
> +              alt=""
missing alt, useful for accessibility

2022-05-05 22:21 UTC, LuigiMenez commented on frontend/src/components/CarrousselNews/index.jsx
>                alt=""
missing alt, useful for accessibility

2022-05-05 22:24 UTC, LuigiMenez requested changes
missing alt, useful for accessibility

2022-05-06 11:39 UTC, LuigiMenez approved these changes, later dismissed
Ok for me.

2022-05-06 12:32 UTC, Elfaram approved these changes, later dismissed

2022-05-06 13:10 UTC, NtGZeko reviewed
change alt

2022-05-06 13:15 UTC, Elfaram submitted a review, later dismissed

2022-05-09 15:27 UTC, Elfaram approved these changes, later dismissed

2022-05-10 07:28 UTC, LuigiMenez approved these changes, later dismissed
Ok for me.

2022-05-10 08:07 UTC, LoicBrassart approved these changes, later dismissed
Saw no Evil

2022-05-10 13:17 UTC, Elfaram approved these changes, later dismissed

2022-05-10 13:58 UTC, SDecambray approved these changes, later dismissed

2022-05-10 14:17 UTC, ghost approved these changes

2022-05-10 14:32 UTC, LuigiMenez approved these changes
Ok for me.

2022-05-10 15:00 UTC, LoicBrassart approved these changes
Saw no Evil

2022-05-10 15:03 UTC, merged