add multi modif in carousel + modif majeur in css
WildCodeSchool/2022-03-JS-Lille-project-2-g3-movies pull request #9
Opened 2022-04-15 13:17 UTC by NtGZeko

2022-04-15 13:19 UTC, Dash293 approved these changes, later dismissed

2022-04-15 13:28 UTC, LoicBrassart requested changes
Remove the "template-fullstack" dependency and it'll be ok

Advice: 
- Be careful with z-index, it **will** add problems later

2022-04-15 13:28 UTC, LoicBrassart commented on backend/package.json
> +    "template-fullstack": "file:.."
Nope, damnit >_<

2022-04-15 13:28 UTC, LoicBrassart commented on frontend/package.json
> +    "template-fullstack": "file:.."
Nope

2022-04-15 13:28 UTC, LoicBrassart commented on frontend/src/components/Header/style.jsx
> +    z-index: 9999;
You shouldn't use z-index like this

2022-04-15 13:28 UTC, LoicBrassart commented on frontend/src/components/Header/style.jsx
> +    z-index: 999;
>_>

2022-04-15 13:28 UTC, LoicBrassart commented on frontend/src/components/Header/style.jsx
> +      z-index: 999;
>_>

2022-04-20 12:05 UTC, NtGZeko commented
modif

2022-04-20 12:21 UTC, SDecambray approved these changes

2022-04-20 14:33 UTC, LuigiMenez approved these changes
Ok for me.

2022-04-20 15:23 UTC, LoicBrassart approved these changes
Nice job on removing at least one `z-index` ! :muscle:

2022-04-20 15:27 UTC, merged